# 1. ????? Kafka (????? ?? Docker)
spring.kafka.bootstrap-servers=${KAFKA_URL:localhost:9092}

# 2. ????????? ????????? (???????????)
# ???? ????????? - ??????? ??????
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# ???????? (???? ???????) - ?????????? Java-?????? ? JSON
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer