spring.datasource.url=${DB_URL:jdbc:postgresql://order-db:5432/order_db}
spring.datasource.username=${DB_USERNAME:order_admin}
spring.datasource.password=${DB_PASSWORD:order_pass_123}



spring.cache.type=redis
spring.data.redis.host=redis_cache
spring.data.redis.port=6379

spring.liquibase.enabled=true