spring.application.name=order-service

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/order_database}
spring.datasource.username=${DB_USERNAME:order_admin}
spring.datasource.password=${DB_PASSWORD:order_pass_123}

# External Services
app.services.user-service.url=${USER_SERVICE_URL:http://localhost:8080}

# JPA & Liquibase
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.cloud.openfeign.circuitbreaker.enabled=true

# ????? Kafka ???????
spring.kafka.bootstrap-servers=${KAFKA_URL:localhost:9092}