spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=password



spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.liquibase.enabled=true
library.jwt.secret=myVerySecretKeyForSigningJWTsTokens2026!