spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false
app.redis.ttl=10m

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

library.jwt.secret=myVerySecretKeyForSigningJWTsTokens2026!

